apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k8igty8jz-go 
  janus-idp.io/tekton: k8igty8jz-go
  backstage.io/kubernetes-id: k8igty8jz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k8igty8jz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  